zmiana occupied z Boolean na RoomStatus, zmiana rozmiejszczenia miedz…
bms-devs/hackathon-heroku-app pull request #11
Opened 2016-12-23 14:17 UTC by xarines

…y pakietami, zwiekszenie czasu odswiezania AJAXem do 5s ( w celu odciazenia heroku)

warto byloby zmienic nazwe pola w Room z occupied na roomStatus, ale wtedy kazdy musialby sie dostosowac (raspberry + bot), wiec na razie nie warto tego robic

klasa do castowania jest tymczasowa, gdy bot przejdzie na nowe api (ktore bedzie wkrotce) to bedzie mozna wywalic stare endpointy oraz ta klase

2016-12-25 22:36 UTC, sprzedwojski requested changes
Nie widzę tutaj żadnej funkcjonalności związanej z "wietrzeniem".
Chyba, że jest to tylko zmiana przygotowawcza, to wtedy ok, ale wydaje mi się, że lepiej wmerge'ować od razu już całą funkcjonalność.

2016-12-25 22:36 UTC, sprzedwojski commented on src/main/java/com/github/britter/springbootherokudemo/entity/enumeration/RoomStatus.java
> +    AVAILABLE, OCCUPIED, UNKNOWN
Czy jest jakaś różnica funkcjonalna w porównaniu do tego, co było wcześniej? Bo ja jej nie widzę.
Wcześniej Boolean mógł mieć wartość True/False/null i sprowadzało się to do tego samego, co w przypadku tego enuma.
Żeby wprowadzić funkcjonalność "wietrzenia" potrzebujemy chyba jeszcze czwartej wartości enuma (np. AIRING - wg. Google Translate "wietrzenie")?

2016-12-26 08:38 UTC, xarines commented on src/main/java/com/github/britter/springbootherokudemo/entity/enumeration/RoomStatus.java
> +    AVAILABLE, OCCUPIED, UNKNOWN
Tak jak napisałeś - to jest tylko zmiana przygotowawcza - zmiany w starym API bez widocznych zmian "z zewnątrz", ale masz racje - lepiej wmegować od razu wszystko, więc jak zrobie to wrzuce PR z dwoma commitami, więc ten można na razie odrzucić

2017-01-07 11:51 UTC, xarines commented
na razie zamykam tego PR, jak dojdzie nowa funkcjonalność to będzie nowy PR

2017-01-07 11:51 UTC, closed without merging